### ISSUE TITLE
Add support for Babel 6.0

### ISSUE THREAD

**Issue by weblogixx** [deepsweet/isparta-loader#4]
Hi @deepsweet,

I just tried to use your loader together with babel 6 and babel-loader 6. It crashes when adding the new required presets option for babel (as seen on http://babeljs.io/docs/plugins/preset-es2015/).

The crash happens with the following error:

ERROR in ./src/config/test.js
Module build failed: ReferenceError: [BABEL] /Users/myuser/Documents/src/github/react-webpack-template/src/config/test.js: Unknown option: /Users/myuser/Documents/src/github/react-webpack-template/.babelrc.presets
    at Logger.error (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Instrumenter.instrumentSync (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta/lib/instrumenter.js:60:55)
    at Object.module.exports (/Users/myuser/Documents/src/github/react-webpack-template/node_modules/isparta-loader/index.js:15:25)

**Comment by weblogixx** [comment]
Update: Sorry, just had a look at the code. Seems like the error comes from isparta directly and has nothing to do with your loader. Closing this now :)
